name: Build and Push Alpine Docker Image

on:
  repository_dispatch:
    types: [caddy-release]
  workflow_dispatch:
    inputs:
      build_version:
        description: 'Caddy version to build (without v prefix, e.g., 2.8.0)'
        required: false

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version if empty
        id: set_version
        run: |
          if [ -n "${{ github.event.inputs.build_version }}" ]; then
            VERSION=$(echo "${{ github.event.inputs.build_version }}" | sed 's/^v//')
          elif [ -n "${{ github.event.client_payload.latest_version }}" ]; then
            VERSION=$(echo "${{ github.event.client_payload.latest_version }}" | sed 's/^v//')
          else
            VERSION=$(cat version.json | jq -r '.version' | sed 's/^v//')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check Caddy version availability
        id: check_version
        run: |
          AVAILABLE_BUILDER_ALPINE=$(curl -sL https://hub.docker.com/v2/repositories/library/caddy/tags/${{ env.VERSION }}-builder-alpine | jq -r '.name')
          AVAILABLE_BASE_ALPINE=$(curl -sL https://hub.docker.com/v2/repositories/library/caddy/tags/${{ env.VERSION }}-alpine | jq -r '.name')
          if [ "$AVAILABLE_BUILDER_ALPINE" != "${{ env.VERSION }}-builder-alpine" ]; then
            echo "Caddy builder version ${{ env.VERSION }}-builder-alpine is not available. Exiting."
            exit 1
          fi
          if [ "$AVAILABLE_BASE_ALPINE" != "${{ env.VERSION }}-alpine" ]; then
            echo "Caddy base version ${{ env.VERSION }}-alpine is not available. Exiting."
            exit 1
          fi

      - name: Build and push Docker image (alpine)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.alpine
          push: true
          build-args: |
            CADDY_VERSION=${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          tags: |
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:${{ env.VERSION }}-alpine
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:alpine
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:${{ env.VERSION }}-alpine
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:alpine

      - name: Clean up Docker images
        run: |
          docker rmi ghcr.io/${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:${{ env.VERSION }}-alpine || true
          docker rmi ghcr.io/${{ secrets.DOCKER_USERNAME }}/caddy-cloudflare:alpine || true
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:${{ env.VERSION }}-alpine || true
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:alpine || true
          docker builder prune --force

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}-alpine
          release_name: "Caddy Alpine v${{ env.VERSION }}"
          body: "New Caddy release detected. See the full release notes [here](https://github.com/caddyserver/caddy/releases/tag/${{ env.VERSION }})."
          draft: false
          prerelease: false