name: Build and Push Docker Image

on:
  repository_dispatch:
    types: [caddy-release]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (standard)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          tags: |
            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-docker:${{ github.event.client_payload.latest_version }}
            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-docker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-docker:${{ github.event.client_payload.latest_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-docker:latest

      - name: Build and push Docker image (alpine)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-alpine
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          tags: |
            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-docker:${{ github.event.client_payload.latest_version }}-alpine
            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-docker:alpine
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-docker:${{ github.event.client_payload.latest_version }}-alpine
            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-docker:alpine

      - name: Clean up Docker images
        run: |
          docker rmi ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-docker:${{ github.event.client_payload.latest_version }} || true
          docker rmi ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-docker:${{ github.event.client_payload.latest_version }}-alpine || true
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-docker:${{ github.event.client_payload.latest_version }} || true
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-docker:${{ github.event.client_payload.latest_version }}-alpine || true
          docker builder prune --force

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.latest_version }}
          release_name: "Caddy Release ${{ github.event.client_payload.latest_version }}"
          body: "New Caddy release detected. See the full release notes [here](https://github.com/caddyserver/caddy/releases/tag/${{ github.event.client_payload.latest_version }})."
          draft: false
          prerelease: false
